import {LedgerTable,type LedgerColumn} from "@/components/ui/LedgerTable";
import {PricingToggle} from "@/components/marketing/PricingToggle";
import type {StatusValue} from "@/components/ui/StatusPill";
import "./landing.css";

type CategoryRow={date:string;description:string;amount:string;credit:boolean;category:string;confidence:"high"|"med"|"low";source:string;status:StatusValue};
const categoryRows:readonly CategoryRow[]=[
  {date:"03 Aug",description:"Payoneer — Bright Studio LLC",amount:"PKR 184,500",credit:true,category:"Client Income",confidence:"high",source:"Payoneer",status:"ok"},
  {date:"05 Aug",description:"Wise — NovaTech Inc",amount:"PKR 96,200",credit:true,category:"Client Income",confidence:"high",source:"Wise",status:"ok"},
  {date:"07 Aug",description:"Bank — Zaid Traders",amount:"PKR 45,000",credit:true,category:"Local Sales",confidence:"med",source:"Bank",status:"ok"},
  {date:"09 Aug",description:"WhatsApp — Ahsan Bhai",amount:"PKR 12,000",credit:true,category:"Client Income",confidence:"low",source:"WhatsApp",status:"review"},
  {date:"10 Aug",description:"Payoneer — Platform Fee",amount:"– PKR 1,840",credit:false,category:"Platform Fees",confidence:"high",source:"Payoneer",status:"ok"},
  {date:"12 Aug",description:"Bank — LESCO Electricity",amount:"– PKR 8,400",credit:false,category:"Utilities",confidence:"high",source:"Bank",status:"ok"},
  {date:"14 Aug",description:"Wise — Figma Subscription",amount:"– PKR 3,200",credit:false,category:"Software & Tools",confidence:"high",source:"Wise",status:"ok"},
  {date:"15 Aug",description:"WhatsApp — Client retainer",amount:"PKR 60,000",credit:true,category:"Client Income",confidence:"med",source:"WhatsApp",status:"ok"},
];
const categoryColumns:readonly LedgerColumn<CategoryRow>[]=[
  {id:"date",header:"Date",render:row=>row.date},{id:"description",header:"Description",render:row=>row.description},
  {id:"amount",header:"Amount",headerClassName:"amount-head",className:row=>`amt-cell ${row.credit?"credit":"debit"}`,render:row=>row.amount},
  {id:"category",header:"Category",render:row=><span className="cat-pill"><span className={`conf-dot ${row.confidence}`}/>{row.category}</span>},
  {id:"source",header:"Source",className:"src-tag",render:row=>row.source},
  {id:"status",header:"Status",status:row=>row.status},
];

const faq=[
  ["Do I have to type anything in manually?","No — that's the whole point. Forward the PDF or screenshot the moment you're paid, and Munshi reads and categorizes it. You only open the app to review the odd flagged entry."],
  ["What if it gets a category wrong?","Correct it once from the dropdown. Munshi remembers that merchant permanently, so the same correction never has to be made twice."],
  ["How do the client payment reminders work?","Each client entry carries the date they agreed to pay. Once that date passes, Munshi drafts a reminder message with their name, the amount owed, and how many days overdue — you just review and send it."],
  ["Is my financial data safe?","Raw statements are never stored — only the extracted, encrypted entries. Nobody at Munshi can see your numbers without your access."],
  ["Does it help at tax time too?","Yes — but that's a bonus, not the main job. Because everything's already categorized and reconciled all year, exporting an FBR-ready summary is one click, any time you need it."],
  ["Can I switch plans later?","Yes, anytime — and your full ledger history moves with you. There's no lock-in and no setup fee either way."],
] as const;
const growth=[{month:"Mar",value:441,height:86},{month:"Apr",value:479,height:94},{month:"May",value:512,height:100},{month:"Jun",value:548,height:107},{month:"Jul",value:574,height:113},{month:"Aug",value:612,height:120}] as const;

function Logo({footer=false}:{footer?:boolean}){return <img className={footer?"footer-logo":"brand-logo"} src="/munshi-logo.png" alt="Munshi logo" width={footer?30:32} height={footer?31:33}/>;}
function Divider(){return <div className="divider"/>;}
function MiniStrip({items}:{items:readonly {value:string;label:string;warn?:boolean}[]}){return <div className="mini-strip">{items.map(item=><div key={item.label}><div className={`num${item.warn?" warn":""}`}>{item.value}</div><div className="lbl">{item.label}</div></div>)}</div>;}
function Folio({number,title,description,preview,children}:{number:string;title:string;description:string;preview:React.ReactNode;children:React.ReactNode}){return <details className="folio-card"><summary><div className="folio-label">{number}</div><h3>{title}</h3><p className="fc-desc">{description}</p>{preview}<span className="open-toggle">Open this screen <span className="arrow">▾</span></span></summary><div className="folio-expand-inner">{children}</div></details>;}

export default function LandingPage(){
  const deadline=new Date(Date.UTC(new Date().getUTCFullYear(),8,30,23,59,59));
  const now=new Date();if(now>deadline)deadline.setUTCFullYear(deadline.getUTCFullYear()+1);
  const diff=Math.max(0,deadline.getTime()-now.getTime()),days=Math.floor(diff/86400000),hours=Math.floor(diff/3600000)%24,mins=Math.floor(diff/60000)%60;
  return <div className="landing">
    <div className="announce">The only Pakistani freelance ledger that <strong>totals your income, tracks what clients still owe — and reminds them for you</strong>.</div>
    <nav className="marketing-nav"><div className="nav-inner"><a className="wordmark" href="/"><Logo/>MUNSHI<span className="dot">.</span></a><div className="tabs"><a href="#register">Register</a><a href="#how">How it works</a><a href="#security">Security</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a><a href="/privacy">Privacy</a></div><a className="nav-cta" href="/login">Open your ledger</a></div></nav>
    <header className="hero"><div className="wrap hero-grid"><div className="hero-copy"><div className="eyebrow">Folio No. 001 — Income, Dues &amp; Bookkeeping, Pakistan</div><h1>Always know what you made,<br/>what&apos;s left, <em>and who still owes you</em>.</h1><div className="unique-tag">✓ Forward it — that&apos;s the whole step. No new app, no manual entry, ever.</div><p className="hero-sub">Munshi reads your Payoneer statements and WhatsApp payments, keeps a running ledger, and tracks what every client still owes — filing-ready summaries come for free, whenever you need them.</p><div className="hero-ctas"><a className="btn-primary" href="#pricing">Open your ledger →</a><a className="btn-ghost" href="#register">See the register</a></div></div>
      <div className="ledger-card"><div className="ledger-head"><span><span className="live-dot"/>Live Register</span><span>Aug 2026</span></div><div className="ledger-body"><div className="ledger-row"><span>12 Aug</span><span>Payoneer — Bright Studio LLC</span><span className="amt credit">PKR 184,500</span></div><div className="ledger-row"><span>13 Aug</span><span>Wise — NovaTech Inc</span><span className="amt credit">PKR 96,200</span></div><div className="ledger-row"><span>14 Aug</span><span>LESCO — Electricity</span><span className="amt debit">– PKR 8,400</span></div><div className="ledger-row current"><span>15 Aug</span><span>WhatsApp — Client retainer</span><span className="amt credit">PKR 60,000</span></div></div><div className="ledger-stats"><div className="lstat"><div className="num">384,260</div><div className="lbl">Left after spend, PKR</div></div><div className="lstat"><div className="num">2</div><div className="lbl">Clients still owing</div></div><div className="lstat"><div className="num">42</div><div className="lbl">Days to filing</div></div></div></div>
    </div></header>
    <Divider/>
    <section id="register"><div className="wrap"><div className="section-head"><div className="eyebrow">The Register</div><h2>Four screens a freelancer actually opens.</h2><p>Tap any folio to open it up — the same screens from the real product, not a marketing simplification of them.</p></div><div className="folio-grid">
      <Folio number="Folio 01 — Overview" title="The Sunday-night page." description="One page, checked once a week — income so far, what's still uncategorized, and who still owes you." preview={<MiniStrip items={[{value:"397,700",label:"Income, Aug"},{value:"1",label:"Needs review",warn:true},{value:"2",label:"Clients owing"}]}/>}><MiniStrip items={[{value:"397,700",label:"Income, PKR"},{value:"1",label:"Needs review",warn:true},{value:"34,000",label:"Owed by clients"}]}/><div className="folio-ledger"><div className="ledger-row"><span>15 Aug</span><span>WhatsApp — Client retainer</span><span className="amt credit">PKR 60,000</span></div><div className="ledger-row"><span>14 Aug</span><span>Wise — Figma Subscription</span><span className="amt debit">– PKR 3,200</span></div><div className="ledger-row"><span>12 Aug</span><span>Bank — LESCO Electricity</span><span className="amt debit">– PKR 8,400</span></div></div></Folio>
      <Folio number="Folio 02 — Statement ingestion" title="It reads what you already send." description="Drop a Payoneer PDF or a WhatsApp payment screenshot. Munshi does the rest — no manual entry." preview={<div className="mini-drop">Drop a statement or screenshot →</div>}><div className="drop-mock"><div className="scan-area"><div className="doc-lines"><div/><div/><div/><div/><div/></div><div className="scan-line active"/></div><div className="dz-label">Extracted entries:</div><div className="extract-list">{[["03 Aug — Payoneer Payout","PKR 184,500"],["05 Aug — Wise Transfer","PKR 96,200"],["07 Aug — WhatsApp — Cash","PKR 12,000"],["09 Aug — Bank — LESCO","– PKR 8,400"]].map(row=><div className="erow show" key={row[0]}><span>{row[0]}</span><span>{row[1]}</span></div>)}</div><div className="stamp-note show">4 entries extracted, folio 02</div></div></Folio>
      <Folio number="Folio 03 — Categorization" title="It categorizes, and it learns." description="Correct a category once — Munshi remembers that merchant for good, so you stop re-teaching it every month." preview={<MiniStrip items={[{value:"7",label:"Categorized"},{value:"1",label:"Needs review",warn:true}]}/>}><div className="cat-card"><div className="cat-summary"><div><div className="num">397,700</div><div className="lbl">Income, PKR</div></div><div><div className="num">385,700</div><div className="lbl">Categorized, PKR</div></div><div><div className="num warn">12,000</div><div className="lbl">Needs review, PKR</div></div></div><LedgerTable rows={categoryRows} columns={categoryColumns} getRowKey={row=>`${row.date}-${row.description}`} getRowStatus={row=>row.status}/></div></Folio>
      <Folio number="Folio 04 — Reports & export" title="It closes the books, on demand." description="Category totals that reconcile on their own, formatted the way FBR expects — export it and hand it off." preview={<MiniStrip items={[{value:"384,260",label:"Net, Aug"}]}/>}><div className="report-card">{[["Client income","PKR 397,700"],["Platform fees","– PKR 1,840"],["Utilities","– PKR 8,400"],["Software & tools","– PKR 3,200"]].map(row=><div className="report-row" key={row[0]}><span>{row[0]}</span><span>{row[1]}</span></div>)}<div className="report-row total"><span>Net income</span><span>PKR 384,260</span></div><button className="export-btn" type="button">Export FBR summary</button></div></Folio>
      <Folio number="Folio 05 — Approvals & payouts" title="Nothing moves without your yes." description="A bill comes in, or a client is owed a refund — Munshi asks first. You approve, then it pays, through a licensed payment rail (Raast / JazzCash / Easypaisa)." preview={<MiniStrip items={[{value:"2",label:"Awaiting approval",warn:true}]}/>}><Approval tag="Bill detected" source="LESCO — via forwarded bill" title="LESCO Electricity Bill" amount="PKR 8,400" due="Due 28 Aug 2026" approve="Approve & Pay"/><Approval tag="Client payout due" source="Refund — Bright Studio LLC" title="Send to client's bank account" amount="PKR 15,000" due="Account on file: •••• 4471" approve="Approve & Send"/><div className="approval-note">This is a working demo of the flow only — real transfers need Munshi to be connected through a licensed payment partner first. Nothing here moves real money yet.</div></Folio>
    </div></div></section>
    <Divider/>
    <section id="how"><div className="wrap"><div className="section-head"><div className="eyebrow">Voucher Sequence</div><h2>Four vouchers to your first closed month.</h2></div><div className="vouchers">{[["01","Connect","Forward a statement or screenshot the moment a payment lands — no separate app to open."],["02","Read","Munshi extracts and categorizes each entry in seconds, and flags anything it isn't sure about."],["03","Reconcile","Categories add up on their own, and every client's balance stays current — export it whenever you actually need it."],["04","Follow up","See which clients are past their due date, and send the drafted reminder — no chasing from memory."]].map(v=><article className="voucher" key={v[0]}><div className="vno">{v[0]}</div><h4>{v[1]}</h4><p>{v[2]}</p></article>)}</div></div></section>
    <Divider/>
    <section className="yearend"><div className="wrap yearend-grid"><div><div className="eyebrow">One More Thing It Does</div><h2>And when September comes, you&apos;re already done.</h2><p>No scramble at year end. Every entry you forwarded all year is already categorized and reconciled, so filing is one export, not a week of digging through statements.</p><ul className="yearend-list"><li>Every Payoneer, Wise and WhatsApp payment already logged</li><li>Categories reconciled month by month, not all at once</li><li>Every client&apos;s due date tracked, reminders drafted the moment they&apos;re late</li><li>One-click FBR-ready summary, for any period you need</li></ul></div><div className="countdown-card"><div className="cd-label">Time left to file, this year</div><div className="countdown-digits"><Countdown value={String(days)} label="Days"/><Countdown value={String(hours).padStart(2,"0")} label="Hours"/><Countdown value={String(mins).padStart(2,"0")} label="Mins"/></div><div className="cd-note">Munshi users are usually export-ready weeks before this.</div><a className="cd-cta" href="#pricing">Get ahead of it →</a></div></div></section>
    <Divider/>
    <section id="growth"><div className="wrap"><div className="section-head"><div className="eyebrow">Growing folio</div><h2>Real books, added every week.</h2></div><div className="growth-grid"><div className="growth-stats">{[["612","Businesses on Munshi"],["1,840","Clients tracked, total"],["PKR 18.4M","Logged this month"],["+38","New ledgers this month"]].map(s=><div className="growth-stat" key={s[1]}><div className="num">{s[0]}</div><div className="lbl">{s[1]}</div></div>)}</div><div className="growth-chart-card"><div className="gc-head">Businesses on Munshi — last 6 months</div><div className="gc-bars">{growth.map(d=><div className="gc-col" key={d.month}><div className="bar-val">{d.value}</div><div className="bar" style={{height:d.height}}/><div className="bar-lbl">{d.month}</div></div>)}</div></div></div></div></section>
    <Divider/>
    <section id="security"><div className="wrap"><div className="section-head"><div className="eyebrow">Your Data, Protected</div><h2>Trusted with the numbers, not just the app.</h2></div><div className="stamps-grid"><Stamp badge="Sealed">Raw statements are never stored — only the extracted, encrypted data.</Stamp><Stamp badge="Private">Only you can see your numbers. Even we can&apos;t, without your access.</Stamp><Stamp badge="FBR Ready">Built for FBR from day one — export-ready, not retrofitted later.</Stamp></div></div></section>
    <Divider/>
    <section id="pricing"><div className="wrap"><div className="section-head"><div className="eyebrow">Tariff</div><h2>Honest pricing, in dollars.</h2></div><PricingToggle/><div className="tariff-note">No setup fee. No lock-in. Cancel anytime — your ledger exports with you. Prices shown in USD; billed in PKR at the daily rate for Pakistani cards.</div></div></section>
    <Divider/>
    <section id="faq"><div className="faq-float-layer" aria-hidden="true"><div className="faq-float f1 c-forest"><span className="qm">?</span>Works with slow internet?</div><div className="faq-float f2 c-brass"><span className="qm">?</span>Support in Urdu?</div><div className="faq-float f3 c-forest"><span className="qm">?</span>Team access for my accountant?</div><div className="faq-float f4 c-brass"><span className="qm">?</span>Export as Excel or PDF?</div></div><div className="wrap faq-content"><div className="section-head"><div className="eyebrow">Questions</div><h2>Before you forward your first statement.</h2></div><div className="faq-list">{faq.map(item=><details className="faq-item" key={item[0]}><summary className="faq-q"><span>{item[0]}</span><span className="plus">+</span></summary><div className="faq-a"><p>{item[1]}</p></div></details>)}</div></div></section>
    <Divider/>
    <Footer/>
  </div>;
}

function Approval({tag,source,title,amount,due,approve}:{tag:string;source:string;title:string;amount:string;due:string;approve:string}){return <div className="approval-card"><div className="approval-head"><span className="approval-tag">{tag}</span><span className="approval-src mono">{source}</span></div><div className="approval-title">{title}</div><div className="approval-amt mono">{amount}</div><div className="approval-due mono">{due}</div><div className="approval-actions"><button className="btn-decline" type="button">Decline</button><button className="btn-approve" type="button">{approve}</button></div></div>;}
function Countdown({value,label}:{value:string;label:string}){return <div className="cd-unit"><div className="cd-num">{value}</div><div className="cd-sub">{label}</div></div>;}
function Stamp({badge,children}:{badge:string;children:React.ReactNode}){return <article className="stamp-card"><div className="stamp-badge settle">{badge}</div><p>{children}</p></article>;}
function Footer(){return <footer><div className="wrap"><div className="foot-cols"><div className="foot-col brand-column"><div className="foot-tag"><Logo footer/>Munshi<span className="footer-dot">.</span></div><div className="foot-sub">Made in Pakistan, for Pakistani freelancers.</div><div className="trust-strip"><div className="trust-chip"><span className="dot"/>256-bit encrypted</div><div className="trust-chip"><span className="dot"/>Raw statements never stored</div></div></div><div className="foot-col"><div className="foot-col-label">Product</div><a href="#register">Register</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div><div className="foot-col"><div className="foot-col-label">Legal</div><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a><span className="foot-line">Registered with SECP, Pakistan</span></div><div className="foot-col"><div className="foot-col-label">Contact</div><a href="mailto:support@munshi.app">support@munshi.app</a><a href="https://wa.me/923001234567" target="_blank" rel="noopener noreferrer" className="foot-line whatsapp">WhatsApp: +92 300 1234567</a><span className="foot-line">Lahore, Pakistan</span></div></div><div className="foot-grid"><div className="foot-disclaimer">Munshi is a bookkeeping and record-keeping tool. It is not a bank, is not licensed to hold or move funds, and never asks for your online banking password. All data comes from statements and screenshots you choose to forward.</div><div className="foot-sub mono">© 2026 Munshi. Folio closed. <a href="/staff">·&nbsp;Staff</a></div></div></div></footer>;}
