import { google, gmail_v1 } from "googleapis";
export const GMAIL_SCOPE="https://www.googleapis.com/auth/gmail.readonly";
export const GMAIL_SENDERS=[{provider:"payoneer",domains:["payoneer.com"]},{provider:"wise",domains:["wise.com","transferwise.com"]},{provider:"upwork",domains:["upwork.com"]},{provider:"fiverr",domains:["fiverr.com"]}] as const;
export type GmailProvider=typeof GMAIL_SENDERS[number]["provider"];
export function oauthClient(){return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI);}
export function providerForSender(sender:string):GmailProvider|null {const email=sender.match(/<([^>]+)>/)?.[1]??sender;const domain=email.split("@").pop()?.toLowerCase();return GMAIL_SENDERS.find(x=>x.domains.some(d=>domain===d||domain?.endsWith(`.${d}`)))?.provider??null;}
export function decodeMessage(payload:gmail_v1.Schema$MessagePart|undefined):string {if(!payload)return"";if(payload.body?.data)return Buffer.from(payload.body.data,"base64url").toString("utf8");return(payload.parts??[]).map(decodeMessage).join("\n").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ");}
export type ParsedEmail={amountMinor:number;currency:string;counterparty:string;transactionId:string;direction:"credit"|"debit"};
const EMAIL_PATTERNS:Record<GmailProvider,{amount:RegExp,counterparty:RegExp,id:RegExp,direction:"credit"|"debit"}>={payoneer:{amount:/(USD|PKR|EUR|GBP)\s*([\d,]+(?:\.\d{1,2})?)/i,counterparty:/(?:from|sender)[:\s]+([^\n,]+)/i,id:/(?:transaction|reference)\s*(?:id|number|#)?[:\s]+([\w-]+)/i,direction:"credit"},wise:{amount:/(USD|PKR|EUR|GBP)\s*([\d,]+(?:\.\d{1,2})?)/i,counterparty:/(?:from|recipient|merchant)[:\s]+([^\n,]+)/i,id:/(?:transfer|transaction|reference)\s*(?:id|number|#)?[:\s]+([\w-]+)/i,direction:"credit"},upwork:{amount:/(USD|PKR|EUR|GBP)\s*([\d,]+(?:\.\d{1,2})?)/i,counterparty:/(?:client|from)[:\s]+([^\n,]+)/i,id:/(?:transaction|reference)\s*(?:id|number|#)?[:\s]+([\w-]+)/i,direction:"credit"},fiverr:{amount:/(USD|PKR|EUR|GBP)\s*([\d,]+(?:\.\d{1,2})?)/i,counterparty:/(?:buyer|from|client)[:\s]+([^\n,]+)/i,id:/(?:order|transaction)\s*(?:id|number|#)?[:\s#]+([\w-]+)/i,direction:"credit"}};
export function parseProviderEmail(provider:GmailProvider,body:string):ParsedEmail|null {const p=EMAIL_PATTERNS[provider],a=p.amount.exec(body),c=p.counterparty.exec(body),id=p.id.exec(body);if(!a||!id)return null;const amountMinor=Math.round(Number(a[2].replace(/,/g,""))*100);if(!Number.isSafeInteger(amountMinor))return null;return{currency:a[1].toUpperCase(),amountMinor,counterparty:c?.[1].trim()??provider,transactionId:id[1],direction:p.direction};}
