import { NextResponse } from "next/server";import { z } from "zod";import { google, gmail_v1 } from "googleapis";import { apiError,bearer } from "@/lib/http";import { adminDb,requireMember } from "@/lib/supabase";import { decryptField,encryptField,fromBytea,toBytea } from "@/lib/crypto";import { decodeMessage,GMAIL_SENDERS,oauthClient,parseProviderEmail,providerForSender } from "@/lib/gmail";
type Tokens=Parameters<ReturnType<typeof oauthClient>["setCredentials"]>[0];
const schema=z.object({business_id:z.string().uuid()});
function header(message:gmail_v1.Schema$Message,name:string){return message.payload?.headers?.find(h=>h.name?.toLowerCase()===name.toLowerCase())?.value??"";}
export const runtime="nodejs";
export async function POST(request:Request){try{const body=schema.parse(await request.json());if(bearer(request)!==process.env.CRON_SECRET)await requireMember(body.business_id);const db=adminDb(),{data:account,error}=await db.from("connected_accounts").select("*").eq("business_id",body.business_id).eq("provider","gmail").eq("status","connected").eq("enabled",true).single();if(error)throw error;const client=oauthClient();client.setCredentials(decryptField<Tokens>(fromBytea(account.encrypted_credentials)));client.on("tokens",async tokens=>{const current=decryptField<Tokens>(fromBytea(account.encrypted_credentials));await db.from("connected_accounts").update({encrypted_credentials:toBytea(encryptField({...current,...tokens}))}).eq("id",account.id);});const gmail=google.gmail({version:"v1",auth:client}),messageIds=new Set<string>(),historyId=account.metadata?.history_id as string|undefined;
let fullSync=!historyId;if(historyId){let pageToken:string|undefined;do{try{const res=await gmail.users.history.list({userId:"me",startHistoryId:historyId,historyTypes:["messageAdded"],maxResults:500,pageToken});res.data.history?.flatMap(h=>h.messagesAdded??[]).forEach(x=>{if(x.message?.id)messageIds.add(x.message.id);});pageToken=res.data.nextPageToken??undefined;}catch(e){if((e as {code?:number}).code!==404)throw e;messageIds.clear();fullSync=true;break;}}while(pageToken);}
if(fullSync){const domains=GMAIL_SENDERS.flatMap(x=>x.domains),after=account.last_synced_at?` after:${Math.floor(new Date(account.last_synced_at).getTime()/1000)}`:" newer_than:7d";const res=await gmail.users.messages.list({userId:"me",q:`{${domains.map(d=>`from:${d}`).join(" ")}}${after}`,maxResults:100});res.data.messages?.forEach(m=>{if(m.id)messageIds.add(m.id);});}
let staged=0,failed=0;for(const id of messageIds){const msg=(await gmail.users.messages.get({userId:"me",id,format:"full"})).data,from=header(msg,"from"),provider=providerForSender(from);if(!provider)continue;const raw=decodeMessage(msg.payload),parsed=parseProviderEmail(provider,raw),sourceId=parsed?.transactionId??id,encrypted=toBytea(encryptField({from,subject:header(msg,"subject"),body:raw}));if(!parsed){await db.from("parsing_failures").insert({business_id:body.business_id,user_id:account.created_by,provider,source_id:id,encrypted_raw_body:encrypted,reason:"Allowed sender email did not match parser"});failed++;continue;}const{error:insertError}=await db.from("staging_transactions").upsert({business_id:body.business_id,user_id:account.created_by,provider,source_id:sourceId,occurred_at:new Date(Number(msg.internalDate??Date.now())).toISOString(),description:`${provider} — ${parsed.counterparty}`,amount_minor:parsed.amountMinor,currency:parsed.currency,direction:parsed.direction,counterparty:parsed.counterparty,encrypted_raw_body:encrypted},{onConflict:"business_id,provider,source_id",ignoreDuplicates:true});if(insertError)throw insertError;staged++;}
const profile=await gmail.users.getProfile({userId:"me"});await db.from("connected_accounts").update({last_synced_at:new Date().toISOString(),metadata:{...account.metadata,history_id:profile.data.historyId}}).eq("id",account.id);return NextResponse.json({staged,failed});}catch(e){return apiError(e);}}
